### ISSUE TITLE
Not usable with extensions-dir

### ISSUE THREAD

**Issue by ChristianToepfer** [JulienCroain/private-extension-manager#4]
Hi Julien,
I am using code with `--extensions-dir`. 
You place an extension to install with `code --install-extension` only, which ends in the default path.

Any other way to install extensions directly without `install-vsix` to support this feature?

Christian

**Comment by JulienCroain** [comment]
Hi Christian,

I use another extension (fabiospampinato.vscode-install-vsix) to proceed installation.
I need to rework all installation process to make it directly or ask to extension's owner to take it in account.

I don't have solution right now but I continue to search for it.

Julien,

**Comment by JulienCroain** [comment]
Hi Christian,

I removed the dependency with fabiospampinato.vscode-install-vsix extension.
I use directly the internal command.
Please try the version 1.4.7 and let me know if all is ok for you.

I made a test with the parameter `-extensions-dir`, but I had to set this parameter too `--user-data-dir`. Even for an installation from the official store otherwise extension is not in the right folder.

Julien,

**Comment by ChristianToepfer** [comment]
Hi Jullien,

that's great, it works fine.
Thanks!

Christian
